### ISSUE TITLE
Kanban board for assignment of tasks - Rails Recipes Project

### ISSUE THREAD

**Issue by limavfabio** [limavfabio/rails_recipes#1]
This issue is related to the Kanban board for the Ruby on Rails project https://github.com/limavfabio/rails_recipes.

There are two members in our group: @limavfabio  and @GhislainMitahi .

Link to the Kanban board: https://github.com/users/limavfabio/projects/1/views/1

**Comment by Gambit142** [comment]
Hi @limavfabio @GhislainMitahi 👋, 

Good job so far!

## Highlights
- Created Kanban board correctly ✔️ 
- All project requirements have cards representing them ✔️

You still need to work on some issues to go to the next project, but you are almost there!

## Required Changes ♻️

- [x] Kindly add project description for the following cards:
- [Build Login and Registration page with Devise](https://github.com/limavfabio/rails_recipes/issues/2)
- [Make sure there are no N+1 queries happening [2 pt]](https://github.com/limavfabio/rails_recipes/issues/8)
- [Create a navigation menu that allows users to open all pages of the app [2 pt]](https://github.com/limavfabio/rails_recipes/issues/9)
- [Write Unit and Integration tests [4 pt]](https://github.com/limavfabio/rails_recipes/issues/10)

- [x] Kindly assign each card in the Kanban board to a team member. For you to verify that the card has been assigned to a team member, you will see n avatar at the bottom right corner of each card as seen in the screenshot below:

![image](https://github.com/limavfabio/rails_recipes/assets/77106962/6cd988e6-8e52-496d-a9e9-b036454ae902)

#### Please ensure that the cards are assigned evenly between team members. 👍 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by limavfabio** [comment]
The reviews comments has been applied.

**Comment by tufoinnkuo10** [comment]
## Status: Approved :heavy_check_mark:

Hi @Team

Your project is complete!  🥇. 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive ✔️
- Task well shared✔️

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
